import { defineConfig } from "orval";

/** Generate from the committed spec with `bun run api:sync`; output is gitignored. */
export default defineConfig({
  api: {
    input: {
      target: "../../apps/be/openapi.json",
    },
    output: {
      mode: "split",
      target: "./src/generated/api.ts",
      schemas: "./src/generated/model",
      client: "react-query",
      override: {
        // Centralize URLs, credentials and error handling.
        mutator: {
          path: "./src/fetcher.ts",
          name: "fetcher",
        },
        fetch: {
          // Return the API envelope directly; fetcher throws on non-2xx responses.
          includeHttpResponseReturnType: false,
        },
        query: {
          useSuspenseQuery: true,
          // Generate server prefetch helpers for query hydration.
          usePrefetch: true,
        },
      },
      // Preserve the Zod output generated by the other entry.
      clean: ["!**/schemas.ts"],
    },
  },

  // Generate request validation from the same API contract.
  zod: {
    input: {
      target: "../../apps/be/openapi.json",
      // Exclude standalone response DTOs; request-body references are still inlined.
      filters: { mode: "exclude", schemas: [/.*/] },
    },
    output: {
      target: "./src/generated/schemas.ts",
      client: "zod",
      override: {
        zod: {
          version: 4,
          // Generate request schemas only; responses have compile-time types.
          generate: {
            body: true,
            param: true,
            query: true,
            header: false,
            response: false,
          },
        },
      },
    },
  },
});
